// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spghxrebelgemdjgxvew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwZ2h4cmViZWxnZW1kamd4dmV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MzMyMDEsImV4cCI6MjA3MDMwOTIwMX0.r6vcx676DvYMMbfd89PuNoYIe-Sx2W1eg2Ac_UMtnS0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});